# frozen_string_literal: true

source 'https://rubygems.org'
ruby '2.5.1'

gem 'pry', group: :development

group :development, :production do
  gem 'json'
  gem 'mechanize'
  gem 'ohm'
  gem 'rake'
  gem 'shotgun'
  gem 'sinatra'
  gem 'slim'
end
