source 'https://rubygems.org'

gem 'haml'
gem 'mechanize'
gem 'ohm'
gem 'redis'
gem 'scss'
gem 'sinatra'
gem 'sinatra-asset-pipeline'
gem 'sinatra-static-assets'

group :development do
  gem 'rake'
end
