# !/usr/bin/env ruby
# -*- ruby -*-
# rubocop:disable Style/HashSyntax

require 'rake/clean'
require 'rake/testtask'

task :default => :test

task :test do
  ruby 'path_to_enlightenment.rb'
end
# rubocop:enable Style/HashSyntax
