# frozen_string_literal: true

source 'http://rubygems.org'

gem 'OptionParser', '0.5.1'
gem 'pry', '0.11.3'
gem 'reek', '5.0.2'
gem 'rubocop', '0.58.1'
gem 'russian_obscenity', '0.0.1'
gem 'terminal-table', '1.8'
