SWEAR_WORDS_ARRAY: 
  - блять
  - блядь
  - бляди
  - ебать
  - ёб
  - бля
  - блядина
  - блядский
  - блядистость
  - блядогон
  - блядословник
  - блядский
  - блядство
  - въебаться
  - взбляд
  - впиздячил
  - выблядовал
  - выблядок
  - выебон
  - выёбывается
  - глупизди
  - доебался
  - ебанёшься
  - ебанул
  - ебашит
  - ёбнул
  - ебало
  - ебанулся
  - ебнул
  - жидоёб
  - жидоёбский
  - заёб
  - изъебнулся
  - заебал
  - заебись
  - козлоёб
  - козлоёбище
  - хуй
  - пизда
  - пиздец
  - \*
  - сука

PRONOUNS_ARRAY: 
  - ты
  - и
  - я
  - в
  - не
  - что
  - на
  - но
  - с
  - как
  - это
  - а
  - он
  - \-
  - –
  - так
  - у
  - за
  - эй
  - то
  - по
  - бы
  - тебе
  - мой
  - же
  - его
  - мы
  - от
  - ведь
  - где
  - про
  - к
  - до
  - чем
  - еще
  - о
  - без
  - Мы
  - —
  -  
