version: '3.6'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/9.5/data

  web:
    build: .
    command:  bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/redmine
    ports:
      - "3000:3000"
    depends_on:
      - db
