version: '3.6'
services:
  db:
    image: postgres
  web:
    build: .
    command:  bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/redmine
    ports:
      - "80:3000"
    depends_on:
      - db
