version: '3.6'
services:
  postgres:
    image: postgres:latest
    restart: always
    networks:
      - redmine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_PASSWORD=redmine'
      - 'POSTGRES_DB=redmine'
      - 'POSTGRES_USER=redmine'
  redmine:
    image: amareelez/redmine:latest
    restart: always
    networks:
      - redmine
    volumes:
      - redmine-data:/usr/src/redmine/files
    ports:
      - 80:3000
    environment:
      - 'REDMINE_DB_POSTGRES=postgres'
      - 'REDMINE_DB_DATABASE=redmine'
      - 'REDMINE_DB_PASSWORD=redmine'
      - 'REDMINE_DB_USER=redmine'
      - 'REDMINE_SECRET_TOKEN=chunky_bacon'
      - 'REDMINE_LANG=en'
volumes:
  postgres-data:
  redmine-data:
networks:
  redmine:
    driver: bridge