# rubocop:disable Lint/ScriptPermission, Lint/UnneededCopDisableDirective
# rubocop:disable Style/HashSyntax, Lint/MissingCopEnableDirective
# !/usr/bin/env ruby
# -*- ruby -*-
require 'rake/clean'
require 'rake/testtask'

task :default => :test

task :test do
  ruby 'path_to_enlightenment.rb'
end
# rubocop:disable Lint/ScriptPermission, Lint/UnneededCopDisableDirective
# rubocop:enable Style/HashSyntax, Lint/MissingCopEnableDirective
