# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'OptionParser'
gem 'rake'
gem 'russian'
gem 'russian_obscenity'
gem 'terminal-table'
