# List of bad Words
bad_words:
  - 'х*й'
  - 'п**д'
  - 'еба*'
  - 'бл*'
  - 'на**й'
  - 'ебал'
  - 'х*есо'
  - 'еб*'
  - 'уе*ан'
  - 'п*зд'
  - 'хуй'
  - 'блять'
  - 'блядь'
  - 'пизд'
  - 'еба'
  - 'нахуй'

# List of excluded words
excluded_words:
  - 'в'
  - 'на'
  - 'о'
  - 'между'
  - 'за'
  - 'под'
  - 'по'
  - 'с'
  - 'без'
  - 'до'
  - 'для'
  - 'у'
  - 'ради'
  - 'к'
  - 'про'
  - 'через'
  - 'сквозь'
  - 'над'
  - 'перед'
  - 'при'
  - 'не'
  - 'ни'
  - 'нет'
  - 'никак'
  - 'пусть'
  - 'пускай'
  - 'давайте'
  - 'да'
  - 'б'
  - 'бы'
  - 'бывало'
  - 'вот'
  - 'вон'
  - 'давай'
  - 'а'
  - 'и'
  - 'именно'
  - 'также'
  - 'тоже'
  - 'как'
  - 'если'
  - 'где'
  - 'когда'
  - 'куда'
  - 'откуда'
  - 'почему'
  - 'лишь'
  - 'едва'
  - 'что'
  - 'чтобы'
  - 'я'
  - 'ты'
  - 'мы'
  - 'меня'
  - 'мой'
  - 'твой'
  - 'тебя'
  - 'он'
  - 'она'
  - 'оно'
  - 'они'
  - 'но'
  - 'это'
  - 'этот'
  - 'тут'
  - 'все'
  - 'там'
  - 'кто'
  - 'так'
  - 'ведь'
  - 'же'
  - 'то'
  - 'ну'
  - '–'
  - 'его'
  - 'себя'
  - 'нету'
  - 'от'
  - 'из'