# frozen_string_literal: true

source 'https://rubygems.org'
ruby '2.5.1'

gem 'pry', group: :development

gem 'shotgun', group: :development

group :development, :production do
  gem 'config'
  gem 'json'
  gem 'mechanize'
  gem 'ohm'
  gem 'parser', '2.4.0.2'
  gem 'rake'
  gem 'sinatra'
  gem 'sinatra-config-file', '~> 1.0'
  gem 'slim'
end
