# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'json'

gem 'faraday'

gem 'mechanize', '2.7.5'

gem 'ohm'

gem 'sinatra'

gem 'shotgun'

gem 'slim', '~> 3.0', '>= 3.0.9'

gem 'thin'

gem 'redis'
