source 'https://rubygems.org'

gem 'mechanize', '~> 2.7', '>= 2.7.6'
gem 'ohm', '~> 3.1', '>= 3.1.1'
gem 'redis', '~> 3.3', '>= 3.3.1'
gem 'sinatra', '~> 1.4', '>= 1.4.7'

group :development do
  gem 'pry'
  gem 'reek'
  gem 'rubocop', '~> 0.54.0'
  gem 'shotgun', '~> 0.9.2'
end
