source 'https://rubygems.org'

gem 'reek'
gem 'rubocop', '~> 0.54.0'

gem 'sinatra', '~> 1.4', '>= 1.4.7'
gem 'redis', '~> 3.3', '>= 3.3.1'
gem 'ohm', '~> 3.1', '>= 3.1.1'
gem 'mechanize', '~> 2.7', '>= 2.7.6' # https://rubygems.org/gems/mechanize
# gem 'capybara', '~> 3.4', '>= 3.4.2' # https://rubygems.org/gems/capybara
gem 'shotgun', '~> 0.9.2'
