# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'faraday'
gem 'mechanize'
gem 'ohm'
gem 'redis'
gem 'shotgun'
gem 'sinatra'
gem 'slim'

